### ISSUE TITLE
Error when running application Zone.assertZonePatched

### ISSUE THREAD

**Issue by lgarro** [AngularClass/angular-starter#1149]
[X] bug report

* **What is the current behavior?**

Running npm run server:dev runs correctly but when I try to access the app while its starting I get

```
main.browser.ts:25TypeError: Zone.assertZonePatched is not a function
    at new NgZone (http://localhost:3000/vendor.bundle.js:35588:14)
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:3000/vendor.bundle.js:26047:22)
    at http://localhost:3000/vendor.bundle.js:26089:59
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:15420:29)
    at Zone.run (http://localhost:3000/polyfills.bundle.js:15313:44)
    at http://localhost:3000/polyfills.bundle.js:15679:58
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:15453:38)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:15353:48)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15585:36)
    at HTMLDocument.ZoneTask.ZoneTask.cancelFn.invoke (http://localhost:3000/polyfills.bundle.js:15525:26)
```

* **What is the expected behavior?**
App start correctly

* **Please tell us about your environment:**

Recently upgraded my respository with all the commits made here from October

- Angular version: 2.1.1
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by lgarro** [comment]
Fixed issue by upgrading zone.js to version ~0.6.23
``` 
"zone.js": "~0.6.23"
```
Even when this fixed the issue why does the version on the repo still has version 0.6.17 and it works
