### ISSUE TITLE
`process` global variable is lost with latest prod build.

### ISSUE THREAD

**Issue by zacharyclaysmith** [AngularClass/angular-starter#1375]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
When building using `npm run build:prod; npm run server:prod` the `process` variable is not defined.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**this was reproduced using a fresh pulldown of the master branch with only the change listed below**

1. add the line `console.debug("PROCESS: ", process);` to the AppComponent (`ngOnInit` works).
2. run the project via `npm run start`
3. something similar to `PROCESS:  Object {title: "browser", browser: true, env: Object, argv: Array[0], version: ""…}` should be displayed in the browser console.
4. run the project via `npm run build:prod` and `npm run server:prod`
5. An error is displayed indicating that `process` is not defined.

* **What is the expected behavior?**
the global `process` variable is defined.

* **What is the motivation / use case for changing the behavior?**
this is a show-stopping bug that breaks any libraries that depend on the `process` polyfill.

* **Please tell us about your environment:**

- Angular version: 2.4.3
- Browser: Version 55.0.2883.95 (64-bit)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Console Error:

ReferenceError: process is not defined
    at t.ngOnInit (http://localhost:8080/main.4eec561b391cebd00e47.bundle.js:1:2544)
    at Wrapper_t.ngDoCheck (/t/t/wrapper.ngfactory.js:16:73)
    at proxyViewClass.View_t_Host0.detectChangesInternal (/t/t/host.ngfactory.js:26:15)
    at proxyViewClass.t.detectChanges (http://localhost:8080/vendor.4e1271d677fc55301287.bundle.js:24:24725)
    at t.detectChanges (http://localhost:8080/vendor.4e1271d677fc55301287.bundle.js:18:28582)
    at http://localhost:8080/vendor.4e1271d677fc55301287.bundle.js:13:13387
    at Array.forEach (native)
    at e.tick (http://localhost:8080/vendor.4e1271d677fc55301287.bundle.js:13:13354)
    at http://localhost:8080/vendor.4e1271d677fc55301287.bundle.js:13:11936
    at t.invoke (http://localhost:8080/polyfills.65bb51041290982e5e46.bundle.js:2:28698)
    at Object.onInvoke (http://localhost:8080/vendor.4e1271d677fc55301287.bundle.js:10:3544)
    at t.invoke (http://localhost:8080/polyfills.65bb51041290982e5e46.bundle.js:2:28638)
    at n.run (http://localhost:8080/polyfills.65bb51041290982e5e46.bundle.js:2:25559)
    at t.run (http://localhost:8080/vendor.4e1271d677fc55301287.bundle.js:10:1896)
    at Object.next (http://localhost:8080/vendor.4e1271d677fc55301287.bundle.js:13:11919)

**Comment by colinskow** [comment]
It appears this is intentional. Feel free to turn it back on in your builds.

[`config/webpack.prod.js#L319`](https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.prod.js#L319)

Meanwhile we can discuss here which Node options should be enabled by default in this repository.

@d3viant0ne do you have an opinion?

**Comment by zacharyclaysmith** [comment]
Thanks for pointing that out, I was apparently looking for something a bit more subtle than a big, giant `process` flag :P. If it's all the same to you guys, I would recommend setting that flag the same way in both prod and dev configurations for consistency.
