### ISSUE TITLE
Custom providers depending on environment

### ISSUE THREAD

**Issue by kristoferjohnsson** [AngularClass/angular-starter#1403]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ x ] question about the decisions made in the repository

* **What is the current behavior?**
In the environment.ts file there is an option to use custom providers depending on if you're in production or development. Ive tried to add an "abstract" class with the useClass: property. So I have 2 different implementations of the abstract class.
 PROVIDERS = [
    ...PROVIDERS,
    {
      provide: EnvironmentConstantsService,
      useClass: EnvironmentProductionConstants
    },
    // custom providers in production
  ];
Everything builds with AOT but when I try to run the application in the browser it seems it cant resolve my provided service. I've also imported and provided the ENV_PROVIDERS from environment.ts in my app.module.  Am I doing something terribly wrong?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

vendor.25a69bd….bundle.js:10248 EXCEPTION: No provider for t!
t.handleError @ vendor.25a69bd….bundle.js:10248
(anonymous) @ vendor.25a69bd….bundle.js:7381
t.invoke @ polyfills.45528f8….bundle.js:2366
onInvoke @ vendor.25a69bd….bundle.js:5145
t.invoke @ polyfills.45528f8….bundle.js:2366
n.run @ polyfills.45528f8….bundle.js:2299
(anonymous) @ polyfills.45528f8….bundle.js:2213
t.invokeTask @ polyfills.45528f8….bundle.js:2382
onInvokeTask @ vendor.25a69bd….bundle.js:5138
t.invokeTask @ polyfills.45528f8….bundle.js:2382
n.runTask @ polyfills.45528f8….bundle.js:2322
i @ polyfills.45528f8….bundle.js:2146
invoke @ polyfills.45528f8….bundle.js:2422
vendor.25a69bd….bundle.js:10249 ORIGINAL STACKTRACE:
t.handleError @ vendor.25a69bd….bundle.js:10249
(anonymous) @ vendor.25a69bd….bundle.js:7381
t.invoke @ polyfills.45528f8….bundle.js:2366
onInvoke @ vendor.25a69bd….bundle.js:5145
t.invoke @ polyfills.45528f8….bundle.js:2366
n.run @ polyfills.45528f8….bundle.js:2299
(anonymous) @ polyfills.45528f8….bundle.js:2213
t.invokeTask @ polyfills.45528f8….bundle.js:2382
onInvokeTask @ vendor.25a69bd….bundle.js:5138
t.invokeTask @ polyfills.45528f8….bundle.js:2382
n.runTask @ polyfills.45528f8….bundle.js:2322
i @ polyfills.45528f8….bundle.js:2146
invoke @ polyfills.45528f8….bundle.js:2422
vendor.25a69bd….bundle.js:10249 Error: DI Error
    at e.v (polyfills.45528f8….bundle.js:2230)
    at e [as constructor] (vendor.25a69bd….bundle.js:3363)
    at e [as constructor] (vendor.25a69bd….bundle.js:13140)
    at new e (vendor.25a69bd….bundle.js:13148)
    at t._throwOrNull (vendor.25a69bd….bundle.js:16767)
    at t._getByKeyDefault (vendor.25a69bd….bundle.js:16778)
    at t._getByKey (vendor.25a69bd….bundle.js:16764)
    at t.get (vendor.25a69bd….bundle.js:16617)
    at e.get [as _AuthService_76] (main.bee1f65….bundle.js:4157)
    at e.getInternal (main.bee1f65….bundle.js:4321)
    at e.get (vendor.25a69bd….bundle.js:10344)
    at e.t.injectorGet (vendor.25a69bd….bundle.js:1117)
    at e.createInternal (main.bee1f65….bundle.js:7409)
    at e.t.createHostView (vendor.25a69bd….bundle.js:1107)
    at t.create (vendor.25a69bd….bundle.js:1042)

**Comment by kristoferjohnsson** [comment]
Bumping,

Anyone who can provide an example of how to use the custom providers depending on environment in environment.ts?

/Kristofer

**Comment by Phmager** [comment]
I think, I have a similiar problem:
"No provider for e!"
"Error: DI Error
    at e.v (http://127.0.0.1:8080/polyfills.e3c51d67029ff8cf235a.bundle.js:3:24282)
    at e [as constructor] (http://127.0.0.1:8080/vendor.d8361ea62561f03f2921.bundle.js:3:40)
    at e [as constructor] (http://127.0.0.1:8080/vendor.d8361ea62561f03f2921.bundle.js:20:24490)
    at new e (http://127.0.0.1:8080/vendor.d8361ea62561f03f2921.bundle.js:20:24819)
    at t._throwOrNull (http://127.0.0.1:8080/vendor.d8361ea62561f03f2921.bundle.js:28:5436)
    at t._getByKeyDefault (http://127.0.0.1:8080/vendor.d8361ea62561f03f2921.bundle.js:28:5792)
    at t._getByKey (http://127.0.0.1:8080/vendor.d8361ea62561f03f2921.bundle.js:28:5346)
    at t.get (http://127.0.0.1:8080/vendor.d8361ea62561f03f2921.bundle.js:28:1708)
    at t.createInternal (http://127.0.0.1:8080/main.d62fa1a91685eb6c913f.bundle.js:7:7931)
    at t.e.create (http://127.0.0.1:8080/vendor.d8361ea62561f03f2921.bundle.js:16:14218)
    at t.create (http://127.0.0.1:8080/vendor.d8361ea62561f03f2921.bundle.js:16:13925)
    at http://127.0.0.1:8080/vendor.d8361ea62561f03f2921.bundle.js:11:13898
    at t.invoke (http://127.0.0.1:8080/polyfills.e3c51d67029ff8cf235a.bundle.js:3:29663)
    at Object.onInvoke (http://127.0.0.1:8080/vendor.d8361ea62561f03f2921.bundle.js:8:11226)
    at t.invoke (http://127.0.0.1:8080/polyfills.e3c51d67029ff8cf235a.bundle.js:3:29603)"

**Comment by Phmager** [comment]
Okay so I found a way:


export function electronServiceFactory() {
  let isElectron = window && (<any>window).process && (<any>window).process.type;

  if (isElectron) {
    return new InteropElectronService();
  } else {
    return new BrowserElectronService();
  }
}


  { provide: ElectronService, useFactory: electronServiceFactory }

**Comment by leolorenzoluis** [comment]
I have the same issue. It breaks on AOT prod especially if I give it just a provider without modifying the implementing class. 

So something like
```
PROVIDERS = [
 ... PROVIDERS,
 SampleService,
 AnotherService
]
```

**Comment by leolorenzoluis** [comment]
For some reason if I declare the providers directly from the module and initialize it there then it works fine, but if I import from environment.ts it's breaking. Something I dont know is causing AOT to choke.

**Comment by raphaelluchini** [comment]
I'm experiencing this problem too :(
