### ISSUE TITLE
tslint@4.4.2 error

### ISSUE THREAD

**Issue by ileler** [AngularClass/angular-starter#1488]
```
ERROR in E:/IRMS/4Source/isli_da/trunk/org.isli.da/org.isli.da.host/src/main/ng2/src/polyfills.browser.ts
Module build failed: Error
    at new FatalError (E:\a0a\.rc\ws\ng2_da\node_modules\.4.4.2@tslint\lib\error.js:33:23)
    at Function.findConfiguration (E:\a0a\.rc\ws\ng2_da\node_modules\.4.4.2@tslint\lib\configuration.js:97:15)
    at resolveOptions (E:\a0a\.rc\ws\ng2_da\node_modules\.3.3.0@tslint-loader\index.js:26:64)
    at Object.module.exports (E:\a0a\.rc\ws\ng2_da\node_modules\.3.3.0@tslint-loader\index.js:110:17)
 @ multi ./~/.2.3.0@webpack-dev-server/client?http://localhost:3000 ./src/polyfills.browser.ts

ERROR in E:/IRMS/4Source/isli_da/trunk/org.isli.da/org.isli.da.host/src/main/ng2/src/main.browser.ts
Module build failed: Error
    at new FatalError (E:\a0a\.rc\ws\ng2_da\node_modules\.4.4.2@tslint\lib\error.js:33:23)
    at Function.findConfiguration (E:\a0a\.rc\ws\ng2_da\node_modules\.4.4.2@tslint\lib\configuration.js:97:15)
    at resolveOptions (E:\a0a\.rc\ws\ng2_da\node_modules\.3.3.0@tslint-loader\index.js:26:64)
    at Object.module.exports (E:\a0a\.rc\ws\ng2_da\node_modules\.3.3.0@tslint-loader\index.js:110:17)
 @ multi ./~/.2.3.0@webpack-dev-server/client?http://localhost:3000 ./src/main.browser.ts
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 543 kB [entry] [rendered]
        [0] ./~/.4.17.4@lodash/lodash.js 540 kB {0} [built]
            [] -> factory:173ms building:3123ms = 3296ms
        [1] (webpack)/buildin/global.js 509 bytes {0} [built]
            [] -> factory:421ms building:207ms = 628ms
        [2] (webpack)/buildin/module.js 517 bytes {0} [built]
            [] -> factory:455ms building:180ms = 635ms
        [3] ./~/.2.28.0@html-webpack-plugin/lib/loader.js!E:/IRMS/4Source/isli_da/trunk/org.isli.da/org.isli.da.host/src/main/ng2/src/index.html 2.14 kB {0} [built]
             factory:154ms building:223ms = 377ms
webpack: Failed to compile.
```
about tslint error! help please...

**Comment by DBosley** [comment]
@ileler I had a very similar error when I tried running `npm run github-deploy` what npm script is outputting that error?

When I ran `npm run github-deploy:prod` I got a different error, and I'm pretty sure the TSLint stuff is actually just a red-herring that's hiding the real problem.

(May be related to #1483)

**Comment by shlomiassaf** [comment]
@ileler This is not helpful.

What command are your running?
