### ISSUE TITLE
Webpack dev middleware failed because of an error while loading 'aspnet-webpack'

### ISSUE THREAD

**Issue by virendra1117** [AngularClass/angular-starter#1574]
System.Exception
Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (C:\Users\virendra gour\AppData\Local\Temp\tmp35B1.tmp:83:19)
at __webpack_require__ (C:\Users\virendra gour\AppData\Local\Temp\tmp35B1.tmp:20:30)
at createWebpackDevServer (C:\Users\virendra gour\AppData\Local\Temp\tmp35B1.tmp:62:26)
at C:\Users\virendra gour\AppData\Local\Temp\tmp36AC.tmp:113:19
at IncomingMessage.<anonymous> (C:\Users\virendra gour\AppData\Local\Temp\tmp36AC.tmp:132:38)
at emitNone (events.js:67:13)
Current directory is: c:\users\virendra gour\documents\visual studio 2015\Projects\Angular2App\Angular2App
at Microsoft.AspNetCore.NodeServices.HostingModels.<InvokeExportAsync>d__7.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNetCore.NodeServices.HostingModels.<InvokeExportAsync>d__13.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNetCore.NodeServices.<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()
System.AggregateException
One or more errors occurred. (Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (C:\Users\virendra gour\AppData\Local\Temp\tmp35B1.tmp:83:19)
at __webpack_require__ (C:\Users\virendra gour\AppData\Local\Temp\tmp35B1.tmp:20:30)
at createWebpackDevServer (C:\Users\virendra gour\AppData\Local\Temp\tmp35B1.tmp:62:26)
at C:\Users\virendra gour\AppData\Local\Temp\tmp36AC.tmp:113:19
at IncomingMessage.<anonymous> (C:\Users\virendra gour\AppData\Local\Temp\tmp36AC.tmp:132:38)
at emitNone (events.js:67:13)
Current directory is: c:\users\virendra gour\documents\visual studio 2015\Projects\Angular2App\Angular2App)
c:\users\virendra gour\documents\visual studio 2015\Projects\Angular2App\Angular2App\Startup.cs
Line 42:              {
Line 43:                  app.UseDeveloperExceptionPage();
Line 44:                  app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {
Line 45:                      HotModuleReplacement = true
Line 46:                  });

**Comment by lee-alderdice** [comment]
Did you fix this?  I have the same error, wondering if it is something to do with environment or routing?

**Comment by daltoncabrera** [comment]
Here solution guys: https://github.com/aspnet/JavaScriptServices/issues/562

**Comment by CodeSpeak11** [comment]
I'm having the same problem. Changed ASPNETCORE_ENVIRONMENT=Production and then  tried removing it altogether. Still getting same error when I deploy to Azure App Service. My app uses Asp.Net Core 1.1 to host a SPA and is using Angular 2.4.5 in case that helps. Runs fine locally regardless of ENVIRONMENT variable setting.
