### ISSUE TITLE
Error: Cannot find module 'tsickle'

### ISSUE THREAD

**Issue by spt110** [AngularClass/angular-starter#1589]
bash-3.2$ npm start

> angular2-webpack-starter@5.4.1 start /Users/sunpeitao/mycode/mydemo/angular2-webpack-starter
> npm run server:dev

> angular2-webpack-starter@5.4.1 server:dev /Users/sunpeitao/mycode/mydemo/angular2-webpack-starter
> webpack-dev-server --config config/webpack.dev.js --open --progress --profile --watch --content-base
src/

Error: Cannot find module 'tsickle'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sunpeitao/mycode/mydemo/angular2-webpack-starter/node_modules/.npmins
tall/@angular/tools/@angular/tsc-wrapped/src/compiler_host.ts:10:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sunpeitao/mycode/mydemo/angular2-webpack-starter/node_modules/.npmins
tall/@angular/tools/@angular/tsc-wrapped/index.ts:9:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sunpeitao/mycode/mydemo/angular2-webpack-starter/node_modules/.npmins
tall/ngc-webpack/1.1.0/src/plugin.ts:2:1)
    at Module._compile (module.js:570:32)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server:dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

**Comment by TaylorPzreal** [comment]
same error when i upgrade angular@4.0.0

**Comment by almothafar** [comment]
Well, I got the same issues, but solved it with clearing out the whole `node_modules` folder and then install modules again, nothing made any sense, but it solved.

**Comment by meorfi** [comment]
weird... the quick hint @almothafar  didn't help for me... I have the latest version of repo pulled w/o any updates

**Comment by Marian0** [comment]
Same error here, using:

- Node v9.4.0
- NPM v5.6.0

```
Error: Cannot find module 'tsickle'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/t/Sites/angular-project/node_modules/ngc-webpack/src/cli/util.js:6:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/t/Sites/angular-project/node_modules/ngc-webpack/src/cli/cli.js:10:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)

```

**Comment by almothafar** [comment]
Are you using `yarn` or `npm` to install modules? 
I highly recommend `yarn`: https://yarnpkg.com/en/

**Comment by meorfi** [comment]
magic happened when I removed `node_modules` and `package-lock.json` file

**Comment by Marian0** [comment]
@almothafar I've been using *npm*.

I installed yarn and do install, now it's working :) 

Thanks
