### ISSUE TITLE
UglifyJs: Unexpected token: name (Codes)

### ISSUE THREAD

**Issue by DanielKucal** [AngularClass/angular-starter#1719]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Executing `npm run build:prod` script ends with the following error:
> ERROR in vendor.47dda95464a1d0c36749.bundle.js from UglifyJs
> Unexpected token: name (Codes) [vendor.47dda95464a1d0c36749.bundle.js:75798,6]

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
It started when I updated my dependencies (`rm -rf node_modules/ && npm install`)
The same behavior is for A2 and A4, I tested it with the newest dependencies from this starter...

Error log from npm-debug.log:
```
14 verbose stack Error: angular2-webpack-starter@5.4.1 build:prod: `npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile --bail`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
* **Please tell us about your environment:**

- Angular version: 4.0.3
- Tested webpack versions: 2.3.1, 2.4.1

**Comment by DanielKucal** [comment]
It was caused by our internal dependency which has been updated and not transpiled to ES5.
