### ISSUE TITLE
Tests break for imports on third-party libraries

### ISSUE THREAD

**Issue by thinkingmedia** [AngularClass/angular-starter#1724]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

Bug Report:

Unable to run Karma/Jasmine tests on TypeScript code that imports third-party libraries (such as lodash, jQuery or Q). Imports yield only undefined variables.

To reproduce start a new Angular starter project:

    git clone --depth 1 https://github.com/angularclass/angular2-webpack-starter.git
    cd angular2-webpack-starter
    npm install
    npm install --save-dev lodash @types/lodash

Add the following lines to the `app.component.ts`

    0:    import _ from 'lodash';
    73:  console.log(_.merge({}, {}));

So that you have the following:

      public ngOnInit() {
        console.log('Initial App State', this.appState.state);
        console.log(_.merge({}, {}));
      }

**What is the expected behavior?**

Run the app and see that everything is working, and that `Object {}` is shown in the JavaScript console.

    npm run server

Run the tests and see that lodash fails to be loaded.

    npm run test

    × should be readly initialized
      Chrome 57.0.2987 (Windows 10 0.0.0)
    TypeError: Cannot read property 'merge' of undefined
        at AppComponent.ngOnInit (webpack:///src/app/app.component.ts:23:37 <- config/spec-bundle.js:73122:599)
        at checkAndUpdateDirectiveInline (webpack:///~/@angular/core/@angular/core.es5.js:10704:0 <- config/spec-bundle.js:11677:19)
        at checkAndUpdateNodeInline (webpack:///~/@angular/core/@angular/core.es5.js:12083:0 <- config/spec-bundle.js:13056:17)
        at checkAndUpdateNode (webpack:///~/@angular/core/@angular/core.es5.js:12051:0 <- config/spec-bundle.js:13024:16)
        at debugCheckAndUpdateNode (webpack:///~/@angular/core/@angular/core.es5.js:12680:21 <- config/spec-bundle.js:13653:59)
        at debugCheckDirectivesFn (webpack:///~/@angular/core/@angular/core.es5.js:12621:0 <- config/spec-bundle.js:13594:13)
        at Object.eval [as updateDirectives] (ng:///DynamicTestModule/AppComponent_Host.ngfactory.js:10:5)
        at Object.debugUpdateDirectives [as updateDirectives] (webpack:///~/@angular/core/@angular/core.es5.js:12606:0 <- config/spec-bundle.js:13579:21)
        at checkAndUpdateView (webpack:///~/@angular/core/@angular/core.es5.js:12018:0 <- config/spec-bundle.js:12991:14)
        at callWithDebugContext (webpack:///~/@angular/core/@angular/core.es5.js:13006:25 <- config/spec-bundle.js:13979:42)
        at Object.debugCheckAndUpdateView [as checkAndUpdateView] (webpack:///~/@angular/core/@angular/core.es5.js:12546:0 <- config/spec-bundle.js:13519:12)
        at ViewRef_.detectChanges (webpack:///~/@angular/core/@angular/core.es5.js:10115:52 <- config/spec-bundle.js:11088:63)
        at ComponentFixture._tick (webpack:///~/@angular/core/@angular/core/testing.es5.js:182:0 <- config/spec-bundle.js:16535:32)
        at webpack:///~/@angular/core/@angular/core/testing.es5.js:196:41 <- config/spec-bundle.js:16549:49
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:381:0 <- config/spec-bundle.js:70195:26)
        at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- config/spec-bundle.js:69710:39)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:380:0 <- config/spec-bundle.js:70194:32)
        at Object.onInvoke (webpack:///~/@angular/core/@angular/core.es5.js:4125:0 <- config/spec-bundle.js:5098:37)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:380:0 <- config/spec-bundle.js:70194:32)
        at Zone.run (webpack:///~/zone.js/dist/zone.js:141:0 <- config/spec-bundle.js:69955:43)
        at NgZone.run (webpack:///~/@angular/core/@angular/core.es5.js:3994:42 <- config/spec-bundle.js:4967:62)
        at ComponentFixture.detectChanges (webpack:///~/@angular/core/@angular/core/testing.es5.js:196:0 <- config/spec-bundle.js:16549:25)
        at Object.<anonymous> (webpack:///src/app/app.component.spec.ts:24:0 <- config/spec-bundle.js:72905:17)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:381:0 <- config/spec-bundle.js:70195:26)
        at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- config/spec-bundle.js:69710:39)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:380:0 <- config/spec-bundle.js:70194:32)
        at Zone.run (webpack:///~/zone.js/dist/zone.js:141:0 <- config/spec-bundle.js:69955:43)
        at Object.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:104:0 <- config/spec-bundle.js:69409:34)
        at webpack:///~/@angular/core/@angular/core/testing.es5.js:96:0 <- config/spec-bundle.js:16449:17
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:381:0 <- config/spec-bundle.js:70195:26)
        at AsyncTestZoneSpec.onInvoke (webpack:///~/zone.js/dist/async-test.js:49:0 <- config/spec-bundle.js:68948:39)
        at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:76:0 <- config/spec-bundle.js:69707:39)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:380:0 <- config/spec-bundle.js:70194:32)
        at Zone.run (webpack:///~/zone.js/dist/zone.js:141:0 <- config/spec-bundle.js:69955:43)
        at AsyncTestZoneSpec._finishCallback (webpack:///~/@angular/core/@angular/core/testing.es5.js:91:0 <- config/spec-bundle.js:16444:25)
        at webpack:///~/zone.js/dist/async-test.js:38:0 <- config/spec-bundle.js:68937:31
        at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:414:0 <- config/spec-bundle.js:70228:31)
        at Zone.runTask (webpack:///~/zone.js/dist/zone.js:181:0 <- config/spec-bundle.js:69995:47)
        at ZoneTask.invoke (webpack:///~/zone.js/dist/zone.js:476:0 <- config/spec-bundle.js:70290:38)
        at timer (webpack:///~/zone.js/dist/zone.js:1491:0 <- config/spec-bundle.js:71305:29)

**What is the motivation / use case for changing the behavior?**

Should be able to load the modules from `node_modules` the same as the when the app is running. Appears that the vendor `lodash` is not added to the `spec-bundle.js` used for testing.

**Please tell us about your environment:**

- Angular version: 4.0.3
- Browser: Chrome 57.0.2987.133 | Windows 10

**Comment by thinkingmedia** [comment]
I've spent a lot of hours in the last 2 days trying to resolve this problem.  I've tried a lot of things and even tried to get tests to debug in WebStorm, but I can't figure out what's wrong.

From what I can if you `require('jquery')` it works fine for dev/prod builds but fails for Karma. If I add a `throw new Error('JQUERY LOADED')` to the `jquery.js` file, then during Karma test runs the error is thrown. jQuery is being required during the tests. Further more, jQuery sees the module.export method and exports correctly.

Inside the TypeScript code the `import $ from 'jquery'` appears to assign `undefined` to `$`.

I'm stumped.

I can't see what is different between the Karma setup and dev/prod builds. So how resolving node_modules is broken, but how I don't know.

Any help would be appreciated. This appears to be a problem with the starter project and other people are going to hit this issue.

**Comment by kuiperr005** [comment]
I'm struggling with the same issue too, any solutions?

**Comment by wronskiPrzemyslaw** [comment]
I have excatly the same problem. Did somebody resolve this problem? I am unable to load third party libraries like jquery, datepicker etc. to the karma tests.

**Comment by wronskiPrzemyslaw** [comment]
Ok i just added my third party librarires files in karma.conf.js like that:
files: [
      { pattern: './node_modules/jquery/dist/jquery.min.js' },
      { pattern: './node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' },
      { pattern: './node_modules/bootstrap-datepicker/dist/locales/bootstrap-datepicker.pl.min.js '},
      { pattern: './node_modules/bootstrap-timepicker/js/bootstrap-timepicker.js' },
      { pattern: './config/spec-bundle.js', watched: false },
      { pattern: './src/assets/**/*', watched: false, included: false, served: true, nocache: false }
    ],
