### ISSUE TITLE
npm run build:aot is not working on Linux

### ISSUE THREAD

**Issue by spiderhc** [AngularClass/angular-starter#1801]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

I'm trying to compile the original project (without modifications) in using "npm run build:aot:prod", but receiving an error.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

1) Clone the original project.
2) Execute the following command:
cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail

-The error just happens when I set "cross-env BUILD_AOT=1".
-The command above is a sub command of "npm run build:aot:prod" (check package.json), that also trigger the error, I separated the exactly point of error to make easier to track.
-This error only happens in Linux (ubuntu) for me, on Windows all is working fine.

* **What is the expected behavior?**

npm run build:aot:prod successfully.

* **What is the motivation / use case for changing the behavior?**
I didn't change anything, just clone and compile.

* **Please tell us about your environment:**
-Linux Ubuntu (on Windows this works fine)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Details about the error I received:**

Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: undefined, resolving symbol ɵf in /home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/core/core.d.ts
    at Error (native)
    at syntaxError (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
    at simplifyInContext (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/@angular/compiler.es5.js:23865:17)
    at StaticReflector.simplify (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/@angular/compiler.es5.js:23877:7)
    at StaticReflector.annotations (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/@angular/compiler.es5.js:23326:38)
    at NgModuleResolver.resolve (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/@angular/compiler.es5.js:13878:34)
    at CompileMetadataResolver.getNgModuleMetadata (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/@angular/compiler.es5.js:14468:58)
    at addNgModule (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/bundles/compiler.umd.js:23050:58)
    at /home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/bundles/compiler.umd.js:23061:14
    at Array.forEach (native)
    at _createNgModules (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/@angular/compiler.es5.js:23055:8)
    at analyzeNgModules (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/bundles/compiler.umd.js:22935:14)
    at analyzeAndValidateNgModules (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/@angular/compiler.es5.js:22940:19)
    at AotCompiler.compileAll (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/@angular/compiler/@angular/compiler.es5.js:22716:13)
    at CodeGenerator.codegen (/home/helmut/Workspaces/Javascript/angular-starter-master/packages/compiler-cli/src/codegen.ts:41:10)
    at /home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/src/main.ts:20:84
    at Object.main (/home/helmut/Workspaces/Javascript/tools/@angular/tsc-wrapped/src/main.ts:116:12)
    at Object.runInternal (/home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/src/main.ts:25:10)
    at /home/helmut/Workspaces/Javascript/angular-starter-master/node_modules/src/plugin.ts:64:21
    at process._tickCallback (node.js:368:9)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by spiderhc** [comment]
I tried again after reinstall everything, and worked fine... 
Sorry
