### ISSUE TITLE
npm run build:aot is not working

### ISSUE THREAD

**Issue by spiderhc** [AngularClass/angular-starter#1810]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Command is not working:

- npm run build:aot

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Run the following commands:

- git clone https://github.com/AngularClass/angular-starter.git
- cd angular-starter
- npm install
- npm run build:aot

* **What is the expected behavior?**

You will see the error:

> > angular-starter@6.0.0 build:aot /home/helmut/Workspaces/Javascript/angular-starter
> npm run build:aot:prod

> angular-starter@6.0.0 build:aot:prod /home/helmut/Workspaces/Javascript/angular-starter
> npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail

> angular-starter@6.0.0 clean:dist /home/helmut/Workspaces/Javascript/angular-starter
> npm run rimraf -- dist

> angular-starter@6.0.0 rimraf /home/helmut/Workspaces/Javascript/angular-starter
> rimraf "dist"

> angular-starter@6.0.0 clean:aot /home/helmut/Workspaces/Javascript/angular-starter
> npm run rimraf -- compiled

> angular-starter@6.0.0 rimraf /home/helmut/Workspaces/Javascript/angular-starter
> rimraf "compiled"

> angular-starter@6.0.0 webpack /home/helmut/Workspaces/Javascript/angular-starter
> node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"

Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: undefined, resolving symbol ɵf in /home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/core/core.d.ts
    at Error (native)
    at syntaxError (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
    at simplifyInContext (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/@angular/compiler.es5.js:23865:17)
    at StaticReflector.simplify (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/@angular/compiler.es5.js:23877:7)
    at StaticReflector.annotations (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/@angular/compiler.es5.js:23326:38)
    at NgModuleResolver.resolve (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/@angular/compiler.es5.js:13878:34)
    at CompileMetadataResolver.getNgModuleMetadata (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/@angular/compiler.es5.js:14468:58)
    at addNgModule (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:23050:58)
    at /home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:23061:14
    at Array.forEach (native)
    at _createNgModules (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/@angular/compiler.es5.js:23055:8)
    at analyzeNgModules (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:22935:14)
    at analyzeAndValidateNgModules (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/@angular/compiler.es5.js:22940:19)
    at AotCompiler.compileAll (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/@angular/compiler/@angular/compiler.es5.js:22716:13)
    at CodeGenerator.codegen (/home/helmut/Workspaces/Javascript/angular-starter/packages/compiler-cli/src/codegen.ts:41:10)
    at /home/helmut/Workspaces/Javascript/angular-starter/node_modules/src/main.ts:20:84
    at Object.main (/home/helmut/Workspaces/Javascript/tools/@angular/tsc-wrapped/src/main.ts:116:12)
    at Object.runInternal (/home/helmut/Workspaces/Javascript/angular-starter/node_modules/src/main.ts:25:10)
    at /home/helmut/Workspaces/Javascript/angular-starter/node_modules/src/plugin.ts:64:21
    at process._tickCallback (node.js:368:9)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-starter@6.0.0 webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@6.0.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/helmut/.npm/_logs/2017-06-22T01_04_47_713Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-starter@6.0.0 build:aot:prod: `npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@6.0.0 build:aot:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/helmut/.npm/_logs/2017-06-22T01_04_47_814Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-starter@6.0.0 build:aot: `npm run build:aot:prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@6.0.0 build:aot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/helmut/.npm/_logs/2017-06-22T01_04_47_852Z-debug.log

* **What is the motivation / use case for changing the behavior?**

This is also affecting "npm run build:docker" command, when I run this command from my personal project the console act as all being successful, but there is a silent error on the point above, that makes some images of my project be missing on nginx.

* **Please tell us about your environment:**

- Ubuntu 16.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

This error occurs at the exact point of the aot command below (following packages.json from "npm run build:aot" you find this occurrence):

- cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail

**Comment by dereklin** [comment]
Not sure if this will fix your issue.  For me, when I stick with these versions, the build runs fine:
```
extract-text-webpack-plugin  2.1.2
typescript                   2.3.4
webpack                      3.0.0
```

**Comment by gdi2290** [comment]
I'm going to be redoing the repo so you can create another issue if this is still a problem

**Comment by akashbiz** [comment]
@gdi2290 when will that new repo will be available? I am facing error when making AoT build when I import a module from common folder outside of src. 
Any idea why AoT doesn't handle the modules loaded from outside folder?
