### ISSUE TITLE
AoT + LazyLoading = Module build failed: Error: Can't resolve './path' in...

### ISSUE THREAD

**Issue by DanielKucal** [AngularClass/angular-starter#1821]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Build fails when one module is loaded lazily into another that is not. 
Maybe it's something for @shlomiassaf 
```
ERROR in ./compiled/src/app/app.module.ngfactory.ts
Module build failed: Error: Can't resolve './+child-detail' in '/Users/danielkucal/Applications/Angular2/angular-starter/src/app'
    at onError (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/Resolver.js:61:15)
    at loggingCallbackWrapper (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/Resolver.js:146:10)
    at loggingCallbackWrapper (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/Resolver.js:133:19)
    at loggingCallbackWrapper (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/danielkucal/Applications/Angular2/angular-starter/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/Resolver.js:146:10)
    at loggingCallbackWrapper (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/Resolver.js:133:19)
    at loggingCallbackWrapper (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/danielkucal/Applications/Angular2/angular-starter/node_modules/tapable/lib/Tapable.js:283:15
    at innerCallback (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/Resolver.js:131:11)
    at loggingCallbackWrapper (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/danielkucal/Applications/Angular2/angular-starter/node_modules/tapable/lib/Tapable.js:283:15
    at resolver.doResolve.createInnerCallback (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/Resolver.js:146:10)
    at loggingCallbackWrapper (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/tapable/lib/Tapable.js:188:11)
    at innerCallback (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/Resolver.js:131:11)
    at loggingCallbackWrapper (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/danielkucal/Applications/Angular2/angular-starter/node_modules/tapable/lib/Tapable.js:283:15
    at resolver.doResolve.createInnerCallback (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/danielkucal/Applications/Angular2/angular-starter/node_modules/enhanced-resolve/lib/Resolver.js:146:10)
 @ ./src/main.browser.aot.ts 10:0-78
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**.
https://github.com/DanielKucal/angular-starter/tree/aot-module-not-resolved-repro
```
git clone https://github.com/DanielKucal/angular-starter angular-starter-aot-error
cd angular-starter-aot-error
git checkout aot-module-not-resolved-repro
npm install
npm run build:aot
```

* **What is the expected behavior?**
Build should pass like in JiT compilation.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 4.1.2 in repro, tested also with 4.2.6
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] doesn't matter

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Question on stackoverflow: https://stackoverflow.com/questions/44989380/angular-module-resolution-with-ahead-of-time-compiler

**Comment by gdi2290** [comment]
I'll be redoing lazy loading a bit so it's easier to work with
