### ISSUE TITLE
Protractor test fails with "Error: Server terminated early with status 1"

### ISSUE THREAD

**Issue by allenhwkim** [AngularClass/angular-starter#499]
- **I'm submitting a ...**
  [x] bug report
- **What is the current behavior?**
  When I run protractor test `$ protractor` after I ran `$ webdriver-manager start`, it fails with error.

```
root directory: C:\repos\angular2-webpack-starter
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver

C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329
      return callbackFn(this.value_);
             ^
Error: Server terminated early with status 1
    at Error (native)
    at C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\remote\index.js:210:20
    at Promise.invokeCallback_ (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
    at TaskQueue.execute_ (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    at TaskQueue.executeNext_ (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    at C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2652:27
    at C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at acquireSession (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:62:22)
    at Function.createSession (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:295:12)
    at Driver (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:778:38)
    at [object Object].DirectDriverProvider.getNewDriver (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\direct.js:69:16)
    at [object Object].Runner.createBrowser (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\built\runner.js:203:37)
    at C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\built\runner.js:293:21
    at _fulfilled (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\akim\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
[launcher] Process exited with error code 1
```
- **What is the expected behavior?**
  It should run without error messages
- **What is the motivation / use case for changing the behavior?**
  N/A
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.13
- Chrome recent version
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

```
$ node -v
v5.10.1

$ npm -v
3.8.5
```

**Comment by gwhite-dayspring** [comment]
I am getting the same issue

**Comment by ranglang** [comment]
I am getting the same issue

**Comment by tamvo94** [comment]
update lasted java sdk 8 :)

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
