### ISSUE TITLE
Issue with router 

### ISSUE THREAD

**Issue by skie** [AngularClass/angular-starter#913]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **current behavior**

On windows7, (nodejs 6.2.2, npm 3.9.5) i clone lastest commit (f0535ba58cee1241739bbbf5dc0b0d79ccf84758) and perform npm install and start dev version.

Loading of home page in brwser lead to next issues:

Home page contains next text on top of page:
<% if (webpackConfig.htmlElements.headTags) { %> <%= webpackConfig.htmlElements.headTags %> <% } %>
Index | Home | Detail | About

Page url contains next text: http://localhost:3000/%3C%=%20webpackConfig.metadata.baseUrl%20%%3E#/home

Issue reproduced in any browser (FF, Chrome, IE10)

**Comment by orlov-vo** [comment]
Restart your computer, maybe help :laughing:

**Comment by skie** [comment]
Funny, but will not help.
Error apeared from one of rc4 commits, sleveral weeks ago. I can do git bisect to detect it if you interested.
In my project branch i just remove all templates related to webpackConfig.metadata to make it works.

**Comment by nowherenone** [comment]
Confirm the issue on Windows 10,  nodejs 6.3.1, npm 3.10.3 
I have all the issues skie has described, plus here is the error I get in console: 

`URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.options.metadata.baseUrl%20%%3E'
    at decodeURIComponent (native)
    at decode_param (C:\Work\abaTrackerWeb\node_modules\express\lib\router\layer.js:167:12)
    at Layer.match (C:\Work\abaTrackerWeb\node_modules\express\lib\router\layer.js:143:15)
    at matchLayer (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:557:18)
    at next (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:216:15)
    at expressInit (C:\Work\abaTrackerWeb\node_modules\express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (C:\Work\abaTrackerWeb\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:312:13)
    at C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:271:10)
    at query (C:\Work\abaTrackerWeb\node_modules\express\lib\middleware\query.js:44:5)
    at Layer.handle [as handle_request] (C:\Work\abaTrackerWeb\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:312:13)
    at C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:176:3)
    at EventEmitter.handle (C:\Work\abaTrackerWeb\node_modules\express\lib\application.js:173:10)
    at Server.app (C:\Work\abaTrackerWeb\node_modules\express\lib\express.js:38:9)
    at Server.new_handler (C:\Work\abaTrackerWeb\node_modules\sockjs\lib\utils.js:89:20)
    at emitTwo (events.js:106:13)
URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.options.metadata.baseUrl%20%%3E'
    at decodeURIComponent (native)
    at decode_param (C:\Work\abaTrackerWeb\node_modules\express\lib\router\layer.js:167:12)
    at Layer.match (C:\Work\abaTrackerWeb\node_modules\express\lib\router\layer.js:143:15)
    at matchLayer (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:557:18)
    at next (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:216:15)
    at expressInit (C:\Work\abaTrackerWeb\node_modules\express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (C:\Work\abaTrackerWeb\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:312:13)
    at C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:271:10)
    at query (C:\Work\abaTrackerWeb\node_modules\express\lib\middleware\query.js:44:5)
    at Layer.handle [as handle_request] (C:\Work\abaTrackerWeb\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:312:13)
    at C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (C:\Work\abaTrackerWeb\node_modules\express\lib\router\index.js:176:3)
    at EventEmitter.handle (C:\Work\abaTrackerWeb\node_modules\express\lib\application.js:173:10)
    at Server.app (C:\Work\abaTrackerWeb\node_modules\express\lib\express.js:38:9)
    at Server.new_handler (C:\Work\abaTrackerWeb\node_modules\sockjs\lib\utils.js:89:20)
    at emitTwo (events.js:106:13)
`

**Comment by nowherenone** [comment]
I've found a solution in another thread: it seems to be a NodeJS issue on Windows:  https://github.com/AngularClass/angular2-webpack-starter/issues/618#issuecomment-230166730

**Comment by stropalov** [comment]
I had this issue on Windows 8, nodejs ~6.3. Just updated to the latest nodejs version 6.9.1 - the problem was gone.

**Comment by skie** [comment]
From what i found this is folder naming issue. so i have moved into folder with short names (remember DOS names 8.3 length). In this case current drive is capital, and node working correctly for such folders.
